---
title: "Untitled"
author: "Kevin Wang"
date: "26/09/2018"
output: html_document
---

```{r}
library(tidyverse)
library(visNetwork)
library(igraph)
```


```{r}
load("RData/cleanedPartnershipData.RData")
```



<!-- ```{r} -->
<!-- # create a network object from each matrix -->
<!-- t0<-as.network(matrix(c(0,1,0, -->
<!--                         0,0,0, -->
<!--                         1,0,0),ncol=3,byrow=TRUE)) -->

<!-- t1<-as.network(matrix(c(0,1,0, -->
<!--                         0,1,0, -->
<!--                         0,0,0),ncol=3,byrow=TRUE)) -->

<!-- t2<-as.network(matrix(c(0,0,0, -->
<!--                         0,1,0, -->
<!--                         0,1,0),ncol=3,byrow=TRUE)) -->



<!-- # convert a list of networks into networkDynamic object -->
<!-- tnet<-networkDynamic(network.list=list(t0,t1,t2)) -->
<!-- render.d3movie(tnet) -->
<!-- ``` -->

# Australia
```{r}
plottingYears = seq(from = 1877, to = 2018, by = 5)
spanYear = 20
```


```{r}
ausNetworkData = cleanedPartnerData %>% 
      dplyr::filter(numberOfPartnerships >= 10,
                    country == "Australia")


ausNetworkDataList = purrr::map(
  .x = plottingYears, 
  .f = ~ dplyr::filter(ausNetworkData, partnershipCareerEnd >= .x - spanYear , partnershipCareerEnd <= .x))

# ausNetworkDataList %>% purrr::map("partnershipCareerEnd") %>% map(mean)

ausGraphList = purrr::map(ausNetworkDataList, igraph::graph_from_data_frame)
# ausGraphCentral = purrr::map_dbl(ausGraphList, ~ centr_degree(.x)$centralization)
ausGraphCentral = purrr::map_dbl(ausGraphList, ~ centr_eigen(.x, directed = FALSE)$centralization)

plot(plottingYears, ausGraphCentral, type = "l")
```


# England 

```{r}
engNetworkData = cleanedPartnerData %>% 
           dplyr::filter(numberOfPartnerships >= 10,
                    country == "England")


engNetworkDataList = purrr::map(
  .x = plottingYears, 
  .f = ~ dplyr::filter(engNetworkData, partnershipCareerEnd >= .x - spanYear , partnershipCareerEnd <= .x))

engGraphList = purrr::map(engNetworkDataList, igraph::graph_from_data_frame)
engGraphCentral = purrr::map_dbl(engGraphList, ~ centr_eigen(.x, directed = FALSE)$centralization)

# plot(plottingYears, engGraphCentral, type = "l")
# lines(plottingYears, ausGraphCentral, col = "red")
```


# Plotting
```{r}
plotdf = bind_rows(
  tibble(plottingYears, networkCentralisation = ausGraphCentral, country = "Australia"),
  tibble(plottingYears, networkCentralisation = engGraphCentral, country = "England")
)

plotdf %>% 
  dplyr::filter(plottingYears >= 1950) %>% 
  ggplot(aes(x = plottingYears, 
             y = networkCentralisation, 
             colour = country)) +
  geom_line(size = 2) +
  scale_color_brewer(palette = "Set1") +
  scale_x_continuous(breaks = plottingYears) +
  theme_classic(18) +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 90))
```


# Ashes results
```{r}
ashesResult = read_csv("ashesResults.csv") %>% janitor::clean_names(case = "lower_camel") %>% 
  dplyr::mutate(years = str_sub(years, 1, 4) %>% as.integer()) %>% 
  dplyr::filter(years > 1950)

ashesResult


g = plotdf %>% 
  dplyr::filter(plottingYears >= 1950) %>% 
  ggplot() +
  geom_line(aes(x = plottingYears, 
             y = networkCentralisation, 
             colour = country), size = 2) +
  theme_classic(18) +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 90),
        legend.title = element_blank())

g

set1Colours = RColorBrewer::brewer.pal(9, "Set1")


g + geom_rug(data = ashesResult, 
               aes(x = years, colour = result), size = 3) +
  scale_x_continuous(breaks = plottingYears[plottingYears >= 1950], limits = c(1930, 2020)) +
  scale_colour_manual(values = c(set1Colours[1], "gray40", set1Colours[2])) +
  annotate(x = 1945, y = 0.65, geom = "text", label = "Series result") +
  labs(x = "years", 
       y = "Network Centralisation")
  # scale_color_brewer(palette = "Set1")
```

