---
title: "Building pressure before taking a wicket"
author: "Kevin Wang"
date: "`r paste0('Initiated on 2020 Aug 22, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

# Summary

# Loading 

## packages
```{r}
library(tidyverse)
library(sjPlot)
library(ggsci)

theme_set(
  theme_classic(18) +
    theme(legend.position = "bottom", 
          panel.grid.minor = element_blank()))
```

## functions
```{r}
clean_over_balls = function(x){
  x %>% 
    tidyr::separate(
      col = "ball", 
      into = c("over", "over_ball"), 
      sep = "[.]", remove = FALSE) %>% 
    dplyr::mutate(
      ball = as_factor(ball), 
      over = over %>% as.integer,
      over_ball = over_ball %>% as.integer(),
      wicket = ifelse(wicket_out %>% complete.cases, "yes", "no") %>% factor())
}
```


## data

```{r}
raw_tbl = readRDS("data/RData/ball_by_ball_22_Aug_2020.rds")
```

# Visualise cumulative runs
```{r}
all_tests = raw_tbl %>% unnest(match_tbl) %>%
  # dplyr::sample_frac(size = 0.001) %>% 
  dplyr::mutate(total_balls_match = purrr::map_int(innings_tbl, nrow)) %>% 
  unnest(innings_tbl) %>% 
  clean_over_balls() %>% 
  dplyr::filter(over_ball <= 6) %>% 
  dplyr::mutate(over_ball = factor(over_ball))

all_tests
```

```{r}
cumruns = all_tests %>% 
  group_by(filename, innings) %>% 
  dplyr::mutate(cumruns = cumsum(runs_batsman),
                innings_balls = seq_along(ball))

cumruns %>% 
  ggplot(aes(x = innings_balls, y = cumruns,
             group = interaction(filename, innings),
             colour = innings)) +
  geom_line(size = 0.5, alpha = 0.5) +
  scale_colour_d3() + 
  facet_grid(innings ~ team1)
```

# Clustering of matches and inngings based on wickets or cum-runs

```{r, eval = FALSE}
x = cumruns %>% 
  ungroup() %>% 
  dplyr::filter(filename == filename[1]) %>% 
  dplyr::pull(runs_total)

y = cumruns %>% 
  ungroup() %>% 
  dplyr::filter(filename == filename[10000]) %>% 
  dplyr::pull(runs_total)

length(x)
length(y)

library(dtw)
tmp = dtw::dtw(x = x, y = y)
# plot(tmp, type = "two")
tmp$distance
tmp$normalizedDistance
```

# Australia tests

```{r, eval = FALSE}
library(ggmap)

venue_vec = cumruns$venue %>% unique

all_venue = purrr::map(
  .x = paste0(cumruns$venue %>% unique, " cricket ground") %>% head,
  .f = ~ ggmap::geocode(location = .x, output = "more"))

names(all_venue) = venue_vec
all_venue = all_venue %>% bind_rows(.id = "venue")
saveRDS(all_venue, file = "data/RData/all_venue.rds")
```

```{r}
aus_tests = cumruns %>% 
  ungroup() %>% 
  dplyr::filter(team1 == "Australia" |
                  team2 == "Australia") %>% 
  dplyr::mutate(
    australia = "Australia", 
    opposite = case_when(
      team1 == "Australia" ~ team2, 
      team2 == "Australia" ~ team1),
    year = str_sub(date, 1, 4))

# aus_tests %>% 
#     distinct(filename, opposite, year)

aus_tests_cumruns = aus_tests %>% 
  group_by(filename, opposite, year, innings) %>% 
  nest()

aus_tests_cumruns
```


## `dtw` against 3rd Ashes test in 2019

```{r}
ashes2019_cumruns = cumruns %>% 
  filter(filename == "data/ball_by_ball_raw//1152848.yaml") %>% 
  filter(innings == "4th innings") %>%
  pull(cumruns)

aus_tests_dtw = aus_tests_cumruns %>% 
  dplyr::mutate(
    dtw_dist = purrr::map_dbl(
      .x = data,
      .f = ~ dtw::dtw(x = .x$cumruns, y = ashes2019_cumruns)$normalizedDistance))
```


```{r}
aus_tests_dtw %>% 
  ggplot(aes(x = opposite, y = dtw_dist)) +
  geom_boxplot() +
  scale_y_log10()
```



# Visualise matches
```{r}
aus_tests_dtw %>% 
  ungroup() %>%
  # filter(filename %in% c("data/ball_by_ball_raw//1152848.yaml", "data/ball_by_ball_raw//518948.yaml")) %>% 
  filter(innings == "4th innings") %>% 
  filter(rank(dtw_dist) <= 5) %>% 
  unnest(data) %>% 
   ggplot(aes(x = innings_balls, y = cumruns,
             group = interaction(filename, innings),
             colour = innings)) +
  geom_line(size = 1.5, alpha = 1) +
  scale_colour_d3() + 
  facet_wrap(winning_team~opposite, scales = "free")
```

# Clustering using distances

```{r}
aus_tests_cluster = aus_tests_dtw %>% 
  dplyr::mutate(
    winning_team = purrr::map_chr(data, ~ unique(.x$winning_team))) %>% 
  ungroup() %>% 
  dplyr::select(-data)

aus_tests_cluster %>% 
  ggplot(aes(x = winning_team, y = dtw_dist,
             colour = innings)) +
  geom_boxplot()
```




# Session Info
```{r}
sessioninfo::session_info()
```

