---
title: "Kevin Wang's template"
author: "Kevin Wang"
date: "`r paste0('Initiated on 2020 Aug 22, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 8
    fig_width: 10
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

# Summary

# Loading 

## packages
```{r}
library(tidyverse)
library(lubridate)

theme_set(theme_classic(18) +
            theme(legend.position = "bottom"))
```

## data

```{r}
raw_batting = read_csv("data/icc_ranking_test/batsmen_ratings_all091217.csv")
raw_batting
```

```{r}
raw_tbl = readRDS("data/RData/ball_by_ball_22_Aug_2020.rds")
all_tests = raw_tbl %>% unnest(match_tbl)
all_tests
```

# Subset to 2010

```{r}
batting2010 = raw_batting %>% 
  dplyr::filter(lubridate::year(rate_date) == "2010")

bbb2010 = all_tests %>% 
  dplyr::filter(str_sub(date, 1, 4) == "2010")

bbb2010
bbb2010$innings_tbl[[1]]
```

# Extract all batters in a match and the match result 
```{r}
batter2010 = bbb2010 %>% 
  dplyr::mutate(
    batter_tbl = purrr::map(
      .x = innings_tbl, 
      .f = ~ .x %>% dplyr::select(batsman, batting_team) %>% dplyr::distinct())) %>% 
  dplyr::select(-gender, -innings_tbl) %>% 
   unnest(batter_tbl) %>% 
  dplyr::mutate(
    date_split = purrr::map(.x = date, .f = ~ str_split(string = .x, pattern = "--")),
    first_date = purrr::map_chr(.x = date_split, ~ .x[[1]][1]) %>% ymd())

batter2010
```

# Matching by player names

The biggest problem is that the ICC data uses a different naming convention compare to Crisheet. 
```{r}
icc_batter_names = batting2010$name %>% unique

head(icc_batter_names)
batter2010$batsman %>% head

cat("Notice not many names are matched")
intersect(icc_batter_names, batter2010$batsman)
```

## Removing all dots seem to do a reasonable job
```{r}
icc_batter_names_rm_dots = icc_batter_names %>% str_remove_all(pattern = "[.]") %>% str_remove_all(pattern = "[-]")
p = gplots::venn(lst(icc_batter_names_rm_dots, batter2010$batsman)) ## The non-intersections are probably due to the absence in the top 100. 

icc_batter2010_cleaned = batting2010 %>% 
  dplyr::mutate(
    batsman = name %>% str_remove_all(pattern = "[.]"))

icc_batter2010_cleaned
```


## Merging with dates in mind
```{r, eval = FALSE}
t1 = batter2010 %>% 
  dplyr::filter(batsman == "GC Smith")

t2 = icc_batter2010_cleaned %>% 
  dplyr::filter(batsman == "GC Smith")

batting_rating = rep(NA, nrow(t1))

for(i in seq_len(nrow(t1))){
  batting_rating[i] = dplyr::last(t2$rating[t2$rate_date <= t1$first_date[i]])
}

batting_rating
```


```{r}

```


# Session Info
```{r}
sessioninfo::session_info()
```

