---
title: "Kevin Wang's template"
author: "Kevin Wang"
date: "`r paste0('Initiated on 2020 Aug 22, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

# Summary

# Loading 

## packages
```{r}
library(tidyverse)
library(sjPlot)

theme_set(
  theme_classic(18) +
    theme(legend.position = "bottom", 
          panel.grid.minor = element_blank()))
```

## functions
```{r}
clean_over_balls = function(x){
  x %>% 
    tidyr::separate(
      col = "ball", 
      into = c("over", "over_ball"), 
      sep = "[.]", remove = FALSE) %>% 
    dplyr::mutate(
      ball = as_factor(ball), 
      over = over %>% as.integer,
      over_ball = over_ball %>% as.integer(),
      wicket = ifelse(wicket_out %>% complete.cases, "yes", "no") %>% factor())
}
```


## data

```{r}
raw_tbl = readRDS("data/RData/ball_by_ball_22_Aug_2020.rds")
```


# Visualise single match

```{r}
test1 = raw_tbl %>% slice(1) %>% unnest(match_tbl) %>% unnest(innings_tbl) %>% 
  clean_over_balls

test1 %>% glimpse()

test1 %>% 
  ggplot(aes(x = over, y = runs_batsman,
             colour = wicket,
             alpha = wicket, 
             size = wicket)) +
  geom_point() +
  scale_y_continuous(breaks = 0:6) +
  scale_colour_brewer(palette = "Set1") +
  scale_alpha_manual(values = c("yes" = 1, "no" = 0.05)) +
  scale_size_manual(values = c("yes" = 3, "no" = 1)) +
  facet_wrap(~innings, scales = "free_x")
```


## NM Lyon

```{r}
lyon = test1 %>% 
  dplyr::filter(bowler == "NM Lyon")

lyon %>% 
  ggplot(aes(x = over, y = runs_batsman,
             colour = wicket,
             alpha = wicket, 
             size = wicket)) +
  geom_point() +
  scale_y_continuous(breaks = 0:6) +
  scale_colour_brewer(palette = "Set1") +
  scale_alpha_manual(values = c("yes" = 1, "no" = 0.5)) +
  scale_size_manual(values = c("yes" = 3, "no" = 1)) +
  facet_wrap(~innings, scales = "free_x")


lyon %>% 
  ggplot(aes(x = over_ball, y = runs_batsman,
             colour = wicket,
             alpha = wicket, 
             size = wicket)) +
  geom_point() +
  scale_y_continuous(breaks = 0:6) +
  scale_colour_brewer(palette = "Set1") +
  scale_alpha_manual(values = c("yes" = 1, "no" = 0.5)) +
  scale_size_manual(values = c("yes" = 3, "no" = 1)) +
  facet_wrap(~innings, scales = "free_x")
```

# Which ball is more likely to take wicket?

Maybe use a series of piecharts.
```{r}
test1 %>% 
  ggplot(aes(x = over_ball, y = runs_batsman,
             colour = wicket,
             alpha = wicket, 
             size = wicket)) +
  geom_point() +
  scale_y_continuous(breaks = 0:6) +
  scale_colour_brewer(palette = "Set1") +
  scale_alpha_manual(values = c("yes" = 1, "no" = 0.5)) +
  scale_size_manual(values = c("yes" = 3, "no" = 1)) +
  facet_wrap(~innings, scales = "free_x")
```

## Logistic model

```{r}
M1 = glm(wicket ~ over + factor(over_ball), family = "binomial", data = test1 %>% dplyr::filter(over_ball <= 6))
summary(M1)

plot_model(M1, type = "pred", digits = 4)
```

# Logistic model on all tests
```{r}
all_tests = raw_tbl %>% unnest(match_tbl) %>% unnest(innings_tbl) %>% 
  clean_over_balls() %>% 
  dplyr::filter(over_ball <= 6)

M2 = glm(wicket ~ over + factor(over_ball), family = "binomial", data = all_tests)

summary(M2)

plot_model(M2, type = "pred", digits = 4)

# qqnorm(M$residuals)
# qqline(M$residuals)
```

# Linear mixed model 
```{r, eval = FALSE}
library(lme4)
M3 = glmer(wicket ~ over + factor(over_ball) + (1 | venue), 
           family = "binomial", data = all_tests)

plot_model(M3, type = "pred", digits = 4)
```


# Session Info
```{r}
sessioninfo::session_info()
```

